[variables]
    PHP_VERSION = '8.3'

[phases.setup]
    nixPkgs = [
        'php83',
        'php83Extensions.pdo_mysql',
        'php83Extensions.exif',
        'php83Extensions.zip',
        'php83Extensions.gd',
        'php83Extensions.redis',
        'php83Extensions.bcmath'
    ]

[phases.build]
    cmds = [
        'npm install',
        'npm run build',
        'composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-reqs'
    ]