[variables]
PHP_VERSION = '8.4'

[phases.setup]
nixPkgs = ['...', 'php84Extensions.pdo_mysql', 'php84Extensions.redis', 'php84Extensions.exif', 'php84Extensions.gd', 'php84Extensions.imagick', 'php84Extensions.soap', 'php84Extensions.bcmath', 'php84Extensions.intl', 'php84Extensions.zip']