# Specify the runtime
node.version = "22"
php.version = "8.3"

# Build command
[build]
  command = "composer install --ignore-platform-reqs --no-dev"

# Start command
[run]
  command = "sh start_railway.sh && /usr/local/bin/frankenphp server --config=/etc/caddy/Caddyfile"